### ISSUE TITLE
Understanding molecular data

### ISSUE THREAD

**Issue by dominikusbrian** [xiangsunlab/durf_hq#2]
Get familiar with MDAnalysis, MDTraj, and Nglview to be able to perform basic analysis and obtain quantitative information about a given molecular dataset.

**Comment by dominikusbrian** [comment]
A Week based issue will replace this one, only a special issue will be added as an extra. Nothing, for now, closing this issue.

**Comment by GustaveLi** [comment]
I have noticed that you have converted the checklist items to issues. It was a really great idea that all the to-dos can be tracked automatically so that I won't mess them up when I drag them manually. Thanks for the effort!
