### ISSUE TITLE
Please learn about NYU Shanghai HPC usage.

### ISSUE THREAD

**Issue by dominikusbrian** [xiangsunlab/durf_hq#6]
Check this link for details:
https://sites.google.com/a/nyu.edu/hpc-nyush/

Your account is now ready, and your login id is your netID and your netID password

**Comment by dominikusbrian** [comment]
Nice! I have seen that you also managed to organize your HPC space and downloaded all the necessary Data. 
Again welcome to the Linux server world and have fun with HPC~

**Comment by GustaveLi** [comment]
I have noticed that you have converted the checklist items to issues. It was a really great idea that all the to-dos can be tracked automatically so that I won't mess them up when I drag them manually. Thanks for the effort!
